swagger: '2.0'
info:
  title: TraderLite Stock Quote API
  x-ibm-name: traderlite-stock-quote-api
  version: 1.2.1
host: $(catalog.host)
schemes:
  - https
basePath: /openldap
produces:
  - application/json
consumes:
  - application/json
security:
  - clientID: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  properties:
    target-url:
      value: 'https://cloud.iexapis.com/stable/stock/'
      description: URL of the proxy policy
      encoded: false
    openldap:
      value: ''
      description: Username from OpenLDAP
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - switch:
          version: 2.0.0
          title: switch
          case:
            - condition: ($operationPath() = '/stock-quote/djia')
              execute:
                - invoke:
                    version: 2.0.0
                    title: /stock-quote/djia
                    header-control:
                      type: blacklist
                      values: []
                    parameter-control:
                      type: whitelist
                      values: []
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error: []
                    target-url: $(target-url)/stock-quote/djia
            - condition: ($operationPath() = '/stock-quote/about')
              execute:
                - invoke:
                    version: 2.0.0
                    title: /stock-quote/about
                    header-control:
                      type: blacklist
                      values: []
                    parameter-control:
                      type: whitelist
                      values: []
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error: []
                    target-url: $(target-url)/stock-quote/about
            - condition: ($operationPath() = '/stock-quote')
              execute:
                - invoke:
                    version: 2.0.0
                    title: /stock-quote
                    header-control:
                      type: blacklist
                      values: []
                    parameter-control:
                      type: whitelist
                      values: []
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error: []
                    target-url: $(target-url)/stock-quote?$(request.querystring)
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
  catalogs:
    sandbox:
      properties:
        openldap: jamilspain
        target-url: 'https://stock-trader-quote.us-south.cf.appdomain.cloud/stocks'
tags: []
definitions:
  Quote:
    properties:
      symbol:
        type: string
        description: The stock ticker symbol
      date:
        type: string
        description: The date of the quote
      time:
        type: integer
        description: The time of the quote
        format: int64
      price:
        type: number
        format: float
        description: The closing price
    additionalProperties: false
  Error:
    properties:
      code:
        type: string
      message:
        type: string
    additionalProperties: false
paths:
  /stock-quote/djia:
    get:
      responses:
        '200':
          schema:
            type: string
          description: success
      produces:
        - application/json
      consumes:
        - application/json
  /stock-quote/about:
    get:
      responses:
        '200':
          schema:
            type: string
          description: success
      produces:
        - application/json
      consumes:
        - application/json
  /stock-quote:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      produces:
        - application/json
      consumes:
        - application/json
    parameters:
      - name: symbols
        in: query
        required: true
        description: Comma separated list of symbols
        type: string
