swagger: "2.0"
info:
  title: TraderLite Stock Quote API
  x-ibm-name: traderlite-stock-quote-api
  version: 1.0.0
schemes:
  - https
basePath: /$(api.properties.openldap)
produces:
  - application/json
consumes:
  - application/json
security:
  - clientID: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  properties:
    target-url:
      value: "https://cloud.iexapis.com/stable/stock/"
      description: URL of the proxy policy
      encoded: false
    openldap:
      value: ""
      description: Username from OpenLDAP
    token:
      value: ""
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - invoke:
          title: invoke
          version: 2.0.0
          verb: GET
          target-url: >-
            https://cloud.iexapis.com/stable/stock/$(request.parameters.symbol)/quote?token=$(api.properties.token)
          follow-redirects: false
          timeout: 60
          parameter-control:
            type: blacklist
          header-control:
            type: blacklist
            values:
              - ^X-IBM-Client-Id$
          inject-proxy-headers: true
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
  catalogs:
    sandbox:
      properties:
        openldap: ldapusername
        token: tokenkey
tags: []
definitions:
  Quote:
    properties:
      symbol:
        type: string
        description: The stock ticker symbol
      date:
        type: string
        description: The date of the quote
      time:
        type: integer
        description: The time of the quote
        format: int64
      price:
        type: number
        format: float
        description: The closing price
    additionalProperties: false
  Error:
    properties:
      code:
        type: string
      message:
        type: string
    additionalProperties: false
paths:
  "/{symbol}":
    get:
      responses:
        "200":
          description: Successful result
          schema:
            $ref: "#/definitions/Quote"
      operationId: getStockQuote
      description: Get a stock quote for the specified symbol
      parameters:
        - name: symbol
          type: string
          required: true
          in: path
          description: Stock symbol
      consumes:
        - application/json
      produces:
        - application/json
