apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
stringData:
  mariadb.db.id: {{ .Values.tradeTransactionalDB.db.user }}
  mariadb.db.pwd: {{ .Values.tradeTransactionalDB.db.password }}
  mongodb.db.id: {{ .Values.tradeHistoryDB.mongodbUsername }}
  mongodb.db.pwd: {{ .Values.tradeHistoryDB.mongodbPassword }}
  apic.stockQuote.clientId: {{ .Values.stockQuoteMicroservice.apic.clientId }}
{{- if and .Values.mqIntegration.enabled }}
  mq.user: {{ .Values.global.mqaccess.user }}
  mq.password: {{ .Values.global.mqaccess.password }}
{{- end }}
{{- if .Values.salesforceIntegration.enabled }}
  salesforce.flow.apiKey: {{ .Values.salesforceIntegration.flow.apiKey }}
{{- end }}
