apiVersion: v2
description: A Helm chart for Kubernetes
name: traderlite
version: 1.0.1
type: application
dependencies:
  - name: mariadb
    version: 7.4.2
    repository: https://charts.bitnami.com/bitnami/
    alias: tradeTransactionalDB
  - name: mongodb
    version: 7.4.2
    repository: https://charts.bitnami.com/bitnami/
    alias: tradeHistoryDB
  - name: kafkaConnect
    version: 1.0.0
    repository: file://kafkaConnect
    condition: kafkaIntegration.enabled
